/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

//#ifndef ROOTOPPDF
//#define ROOTOPPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "TSpline.h"
#include "RooListProxy.h"
#include "Math/Interpolator.h"

using namespace RooFit;
 
class SplinePdf : public RooAbsPdf {
public:
  SplinePdf() {} ; 
  SplinePdf(const char *name, const char *title,
	      RooAbsReal& _x, RooAbsReal& _a,RooAbsReal& _b,TSpline3 _spl);
  SplinePdf(const SplinePdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new SplinePdf(*this,newname); }
  inline virtual ~SplinePdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy a ;
  RooRealProxy b ;
  TSpline3 spl;
  
  Double_t evaluate() const ;

private:

  ClassDef(SplinePdf,1) // Your description goes here...
};
 
//#endif
